# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_question_text', models.CharField(max_length=200)),
                ('answer_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_question_text', models.CharField(max_length=200)),
                ('right_answer1', models.CharField(max_length=200)),
                ('right_answer2', models.CharField(max_length=200)),
                ('false_answer1', models.CharField(max_length=200)),
                ('false_answer2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_question_text', models.CharField(max_length=200)),
                ('right_answer', models.CharField(max_length=200)),
                ('false_answer1', models.CharField(max_length=200)),
                ('false_answer2', models.CharField(max_length=200)),
                ('false_answer3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TFQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_question_text', models.CharField(max_length=200)),
                ('true_or_false', models.BooleanField(default=False, help_text=b'asdasdasd')),
            ],
        ),
    ]
