# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_essayquestion_multiplechoicequestion_singlechoicequestion_tfquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayquestion',
            name='foreign_key_quiz_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='correct_answer_1',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='correct_answer_2',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='correct_answer_3',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='correct_answer_4',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='foreign_key_quiz_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlechoicequestion',
            name='correct_answer_1',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlechoicequestion',
            name='foreign_key_quiz_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tfquestion',
            name='foreign_key_quiz_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
