# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20161116_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayquestion',
            name='foreign_key_quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_2',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_3',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_4',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='foreign_key_quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='foreign_key_quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='tfquestion',
            name='foreign_key_quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
    ]
