# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20161116_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essayquestion',
            old_name='foreign_key_quiz_id',
            new_name='quizfk',
        ),
        migrations.RenameField(
            model_name='multiplechoicequestion',
            old_name='foreign_key_quiz_id',
            new_name='quizfk',
        ),
        migrations.RenameField(
            model_name='singlechoicequestion',
            old_name='foreign_key_quiz_id',
            new_name='quizfk',
        ),
        migrations.RenameField(
            model_name='tfquestion',
            old_name='foreign_key_quiz_id',
            new_name='quizfk',
        ),
        migrations.AddField(
            model_name='singlechoicequestion',
            name='correct_answer_2',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_1',
            field=models.BooleanField(help_text=b'*       clear = False | Checked = True'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_2',
            field=models.BooleanField(help_text=b'*       clear = False | Checked = True'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_3',
            field=models.BooleanField(help_text=b'*       clear = False | Checked = True'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_4',
            field=models.BooleanField(help_text=b'*       clear = False | Checked = True'),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='correct_answer_1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tfquestion',
            name='true_or_false',
            field=models.BooleanField(default=False, help_text=b'*clear = False | Checked = True'),
        ),
    ]
