# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20161116_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlechoicequestion',
            old_name='false_answer1',
            new_name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='false_answer1',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='false_answer2',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='right_answer1',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='right_answer2',
        ),
        migrations.RemoveField(
            model_name='singlechoicequestion',
            name='correct_answer_1',
        ),
        migrations.RemoveField(
            model_name='singlechoicequestion',
            name='correct_answer_2',
        ),
        migrations.RemoveField(
            model_name='singlechoicequestion',
            name='false_answer2',
        ),
        migrations.RemoveField(
            model_name='singlechoicequestion',
            name='false_answer3',
        ),
        migrations.RemoveField(
            model_name='singlechoicequestion',
            name='right_answer',
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='answer_text1',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='answer_text2',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='answer_text3',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='answer_text4',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='question_type',
            field=models.CharField(default=b'multiplechoice', max_length=200),
        ),
        migrations.AddField(
            model_name='singlechoicequestion',
            name='answer_text1',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='singlechoicequestion',
            name='answer_text2',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='singlechoicequestion',
            name='answer_text3',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='singlechoicequestion',
            name='answer_text4',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='singlechoicequestion',
            name='question_type',
            field=models.CharField(default=b'singlechoice', max_length=200),
        ),
    ]
