# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20161123_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoicequestion',
            old_name='question_text',
            new_name='multi_question_text',
        ),
    ]
