# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20161123_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayquestion',
            name='question_type',
            field=models.CharField(default=b'essay', max_length=200),
        ),
        migrations.AddField(
            model_name='tfquestion',
            name='question_type',
            field=models.CharField(default=b'truefalse', max_length=200),
        ),
    ]
