# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20161122_1325'),
        ('quiz', '0011_auto_20161125_1742'),
    ]

    operations = [
    ]
