# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_merge_20161128_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ergebnis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=200)),
                ('punkte', models.IntegerField(max_length=10)),
            ],
        ),
    ]
