# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_ergebnis_punkte'),
    ]

    operations = [
        migrations.AddField(
            model_name='ergebnis',
            name='punkte',
            field=models.IntegerField(default=0),
        ),
    ]
