# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_ergebnis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ergebnis',
            name='punkte',
            field=models.IntegerField(),
        ),
    ]
