# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20161202_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayquestion',
            name='question_type',
            field=models.CharField(default='essay', max_length=200),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='answer_text1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='answer_text2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='answer_text3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='answer_text4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_1',
            field=models.BooleanField(help_text='*       clear = False | Checked = True'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_2',
            field=models.BooleanField(help_text='*       clear = False | Checked = True'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_3',
            field=models.BooleanField(help_text='*       clear = False | Checked = True'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_4',
            field=models.BooleanField(help_text='*       clear = False | Checked = True'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question_type',
            field=models.CharField(default='multiplechoice', max_length=200),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='answer_text1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='answer_text2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='answer_text3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='answer_text4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='question_type',
            field=models.CharField(default='singlechoice', max_length=200),
        ),
        migrations.AlterField(
            model_name='tfquestion',
            name='question_type',
            field=models.CharField(default='truefalse', max_length=200),
        ),
        migrations.AlterField(
            model_name='tfquestion',
            name='true_or_false',
            field=models.BooleanField(default=False, help_text='*clear = False | Checked = True'),
        ),
    ]
