# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer_singlechoice_question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_text',
            new_name='true',
        ),
    ]
