# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_singlechoice_question', '0003_auto_20161110_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_4',
        ),
        migrations.AlterField(
            model_name='question',
            name='true',
            field=models.CharField(max_length=200),
        ),
    ]
