# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer_singlechoice_question', '0005_auto_20161110_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_text1',
            new_name='answer_text_1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_text2',
            new_name='answer_text_2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_text3',
            new_name='answer_text_3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_text4',
            new_name='answer_text_4',
        ),
    ]
