# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_multiplechoice_question', '0004_auto_20161110_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text1',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text2',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text3',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text4',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
