# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_multiplechoice_question', '0008_auto_20161110_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer_1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer_2',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer_3',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer_4',
            field=models.BooleanField(),
        ),
    ]
