# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_multiplechoice_question', '0010_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
